name: Upload Python Package

on:
  push: {}

  pull_request: {}

  release:
    types: [created]

jobs:
  quality:
    name: Code QA
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==23.1.0 flake8==6.0.0 isort==5.10.1

      - name: Run black
        run: black --check .

      - name: Run flake8
        run: flake8 .

      - name: Run isort
        run: isort --check-only --profile black .

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: quality

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tests
        run: tox

  release:
    if: ${{ github.event_name == 'release' }}
    name: Release
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Build the package
        run: poetry build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install twine
          twine upload dist/*

#      - name: Publish to Conda
#        env:
#          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
#        run: |
#          python -m pip install conda-build anaconda-client
#          conda config --set anaconda_upload yes
#          conda-build .

      - name: Build documentation
        run: |
          python -m pip install sphinx sphinx-rtd-theme sphinxcontrib-napoleon sphinx-sitemap
          sphinx-build -b html docs/source/ docs/_build/html/

      - name: Deploy to ReadTheDocs
        run: |
          curl -X POST "https://readthedocs.org/api/v3/projects/eocanvas/builds/" \
            -H "Authorization: Token ${{ secrets.RTD_TOKEN }}"
